framework:
    secret: '%env(APP_SECRET)%'
    trusted_hosts: ['%env(default:trusted_hosts_default:TRUSTED_HOSTS)%']
    http_client: ~
    router:
        utf8: true
    csrf_protection:
        stateless_token_ids: ['jira_api']
