framework:
    default_locale: fr
    enabled_locales: ['fr', 'en']
    set_locale_from_accept_language: true
    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
